# Generated by Django 4.0.4 on 2022-05-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recievedkit',
            field=models.BooleanField(default=False),
        ),
    ]
