# Generated by Django 4.0.4 on 2022-05-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techutsav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=60, null=True)),
                ('no_of_participants', models.CharField(blank=True, default='Not Mentioned', max_length=60, null=True)),
                ('proj_phno', models.CharField(blank=True, max_length=100, null=True)),
                ('teammates', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='events/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('workshop_name', models.CharField(blank=True, max_length=60, null=True)),
                ('workshop_more', models.CharField(blank=True, max_length=60, null=True)),
                ('workshop_max_participants', models.CharField(blank=True, default='Not Mentioned', max_length=60, null=True)),
                ('workshop_extra', models.TextField(blank=True, null=True)),
                ('workshop_rules', models.TextField(blank=True, null=True)),
                ('workshop_phno', models.CharField(blank=True, max_length=100, null=True)),
                ('workshop_venue', models.CharField(blank=True, default='Soon', max_length=100, null=True)),
                ('workshop_timing', models.CharField(blank=True, default='Soon', max_length=100, null=True)),
                ('thumbnail_front', models.FileField(blank=True, null=True, upload_to='workshops/')),
                ('thumbnail_back', models.FileField(blank=True, null=True, upload_to='workshops/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
