# Generated by Django 4.0.4 on 2022-05-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techutsav', '0002_project_workshop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='workshop_extra',
            new_name='event_extra',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='workshop_max_participants',
            new_name='event_max_participants',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='workshop_more',
            new_name='event_more',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='workshop_name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='workshop_phno',
            new_name='event_phno',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='workshop_rules',
            new_name='event_rules',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='workshop_timing',
            new_name='event_timing',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='workshop_venue',
            new_name='event_venue',
        ),
    ]
