# Generated by Django 4.0.4 on 2022-05-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techutsav', '0005_remove_project_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='proj_phno',
            new_name='phone_number',
        ),
    ]
