# Generated by Django 4.0.4 on 2022-05-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techutsav', '0006_rename_proj_phno_project_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mca',
            name='rules',
            field=models.BooleanField(default=True),
        ),
    ]
