# Generated by Django 4.0.4 on 2022-05-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techutsav', '0007_mca_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mca',
            old_name='rules',
            new_name='is_prize',
        ),
    ]
