# Generated by Django 4.0.4 on 2022-05-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techutsav', '0008_rename_rules_mca_is_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='arch',
            name='is_prize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='civil',
            name='is_prize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cse',
            name='is_prize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='is_prize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ece',
            name='is_prize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eee',
            name='is_prize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='it',
            name='is_prize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ma',
            name='is_prize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='me',
            name='is_prize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='is_prize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='is_prize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_prize',
            field=models.BooleanField(default=True),
        ),
    ]
