# Generated by Django 4.0.4 on 2022-05-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techutsav', '0009_arch_is_prize_civil_is_prize_cse_is_prize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arch',
            name='thumbnail_front',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='civil',
            name='thumbnail_front',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cse',
            name='thumbnail_front',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='thumbnail_front',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ece',
            name='thumbnail_front',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eee',
            name='thumbnail_front',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='it',
            name='thumbnail_front',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ma',
            name='thumbnail_front',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mca',
            name='thumbnail_front',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='me',
            name='thumbnail_front',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='thumbnail_front',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='thumbnail_front',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='thumbnail_front',
            field=models.URLField(blank=True, null=True),
        ),
    ]
